//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by tpc.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define ID_VIEW_ARRANGE                 127
#define IDR_MAINFRAME                   128
#define IDR_TPCTYPE                     129
#define IDB_BITMAP1                     130
#define IDD_LOADDATA                    130
#define IDB_BITMAP2                     131
#define IDD_TRACELEVEL                  137
#define IDD_TESTSR                      138
#define IDD_TESTGETESTACION             140
#define IDD_SELECT_AGV_HISTORY          141
#define IDD_INSERTARAGVDLG              142
#define IDD_CARGABAT                    143
#define IDD_TESTGENORD                  144
#define IDD_TIEMPOORDEN                 145
#define IDD_TIMEDLG                     146
#define IDD_FTF_HISTORY                 147
#define IDB_BITMAP3                     151
#define IDD_DIALOG_STOP_PLC             152
#define IDS_COMPREFIX                   0x310
#define IDS_COMPORTERROR                821
#define IDC_FILENAME                    1000
#define IDC_LOADFILE                    1003
#define IDC_CURLINE                     1005
#define IDC_FICHERONMP                  1006
#define IDC_FICHEROAREA                 1007
#define IDC_TRACE                       1007
#define IDC_BROWSEAREA                  1008
#define IDC_AVISO                       1008
#define IDC_TIPOTEL                     1008
#define IDC_LOADAREA                    1009
#define IDC_WARNING                     1009
#define IDC_BROWSEFILE                  1010
#define IDC_ERROR                       1010
#define IDC_EDIT1                       1010
#define IDC_BROWSEFNMP                  1011
#define IDC_FATAL                       1011
#define IDC_EDIT2                       1011
#define IDC_SAVE                        1012
#define IDC_EDIT3                       1012
#define IDC_LOAD                        1013
#define IDC_EDIT4                       1013
#define IDC_EDIT5                       1014
#define IDC_EDIT6                       1015
#define IDC_EDIT7                       1016
#define IDC_EDIT8                       1017
#define IDC_TRACE2                      1017
#define IDC_EDIT9                       1018
#define IDC_AVISO2                      1018
#define IDC_EDIT10                      1019
#define IDC_PTOCOM                      1019
#define IDC_WARNING2                    1019
#define IDC_EDIT11                      1020
#define IDC_POSICION                    1020
#define IDC_ERROR2                      1020
#define IDC_EDIT12                      1021
#define IDC_LADO                        1021
#define IDC_FATAL2                      1021
#define IDC_EDIT13                      1022
#define IDC_CODCLIND                    1022
#define IDC_EDIT14                      1023
#define IDC_EDIT_SELAGV                 1023
#define IDC_EDIT15                      1024
#define IDC_NUMAGVINS                   1024
#define IDC_EDIT16                      1025
#define IDC_POSINS                      1025
#define IDC_EDIT17                      1026
#define IDC_CARGARCHECK                 1026
#define IDC_EDIT18                      1027
#define IDC_NUMAGV                      1027
#define IDC_EDIT19                      1028
#define IDC_CODEST                      1028
#define IDC_TIPEST                      1029
#define IDC_RADIO1                      1033
#define IDC_RADIO2                      1034
#define IDC_PARTIDAORDEN                1034
#define IDC_RADIO3                      1035
#define IDC_AUGMENTOTIEMPO              1035
#define IDC_RADIO4                      1036
#define IDC_SLIDER1                     1036
#define IDC_RADIO5                      1037
#define IDC_SLIDER2                     1037
#define IDC_RADIO6                      1038
#define IDC_FRECUENCIAORDEN             1038
#define IDC_RADIO7                      1039
#define IDC_TIMEPICKER                  1039
#define IDC_RADIO8                      1040
#define IDC_DATETIMEPICKER2             1040
#define IDC_LIST_FTFOHNEHIST            1041
#define IDC_LIST_FTFMITHIST             1042
#define IDC_HIST_KOLLISION              1043
#define IDC_HIST_DEADLOCK               1044
#define IDC_HIST_ALLGEM                 1045
#define IDC_FTF_ZU_HIST                 1046
#define IDC_FTF_NO_HIST                 1047
#define IDS_READERROR                   32113
#define IDS_SENDERROR                   32114
#define ID_VER_TESTMENSAJES             32771
#define ID_VER_CARGARDATOS              32772
#define ID_VER_TESTTHREAD               32773
#define ID_VER_ARRANCARCOMFTS           32774
#define ID_VER_READBLOCKTAB             32775
#define ID_VER_FILTROTRACE              32776
#define ID_VER_TESTESTACIN              32777
#define IDD_TESTESTACION                32778
#define ID_WRITEAGVHISTORY              32779
#define IDS_CARGABAT                    32780
#define IDD_TESTSR_Q                    32781
#define ID_HERRAMIENTAS_TESTGENORDENES  32782
#define IDS_READSITSTOP                 32783
#define IDD_TEST_STOP_PLC_COMS          32784
#define IDD_AUTOTRAFFICCONTROL          32785
#define ID_HERRAMIENTAS_GUARDARPOSICIONESAGVS 32786
#define IDS_MSGTIME                     61204
#define IDS_MSGMODULE                   61205
#define IDS_MSGMESSAGE                  61206
#define IDS_MSGFILE                     61207
#define IDS_MSGLINE                     61208
#define IDS_MSGTYPE                     61209
#define IDS_FILEPATH                    61210
#define IDS_BLOCKNUMBERERROR            61211
#define IDS_BLOCKDISTANCEERROR          61212
#define IDS_NOORDBORRAR                 61213
#define IDS_NOORDMODIFICAR              61214
#define IDS_NOLOGPATHSET                61215
#define IDS_NOAGVCOMPORTSET             61216
#define IDS_NOORACLEUSER                61217
#define IDS_NOAGVHISTORY                61218
#define IDS_ERROR_AGVHIST               61219
#define ID_SIMULATECOM                  61220
#define ID_GENERATESIMORDERS            61221
#define IDS_INSERTARAGV                 61222
#define IDS_INSERTARAGVMP               61223
#define IDS_CARGARBAT                   61224
#define IDS_FILE_SITUATION_FV           61225
#define IDS_ASITUATION                  61226
#define IDS_VSITUATION                  61227
#define IDS_CARGADOROCUPADO             61228
#define IDS_NOCARGADOR                  61229
#define IDS_AGVNOTFOUND                 61230
#define IDS_ERRSIEMENSSR                61231
#define ID_TIEMPOORDEN                  61232
#define IDS_FILE_SITUATION_FE           61233
#define IDS_AGV_WITHOUT_MP              61234
#define IDS_AGV_WITH_EMPTY_CRASH_PROTECT_AREA 61235
#define IDS_CLOSE_WARNING               61236
#define ID_SCROLL_LIST                  61237
#define IDS_SIEMENS_FATAL               61238
#define IDS_NOHISTFILEPATHSET           61239
#define IDS_CANNOT_OPEN_BIN_BLOCKFILE   61240
#define IDS_BLOCKNUMBER_ERROR           61241
#define IDS_ERROR_READ_BLOCKTABLE_INDEX_VECTOR 61242
#define IDS_ERROR_READ_BLOCKTABLE_CRASH_DISTANCES 61243

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        155
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1048
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
